import { products } from "@/types";

export const AllProducts: products[] = [
    {
        "id": 1,
        "Name": "Eau Sauvage",
        "Brand": "Christian Dior",
        "Year": "1966",
        "rating": "4",
        "Country": "France",
        "Image": "https://d2k6fvhyk5xgx.cloudfront.net/images/eau-sauvage.jpg",
        "Gender": "men",
        "Price": 152.99,
        "countInStock" : 5,
        
       
    },
    {
        "id":2,
        "Name": "Dior Sauvage",
        "Brand": "Christian Dior",
        "Year": "2015",
        "rating": "4",
        "Country": "France",
        "Image": "https://m.media-amazon.com/images/I/71W1WNZOwwL._AC_SL1500_.jpg",
        "Gender": "men",
        "Price": 226.99,
        "countInStock" : 5,
    },
    {
        "id":3,
        "Name": "Creed Neroli Sauvage",
        "Brand": "Creed",
        "Year": "1994",
        "rating": "4",
        "Country": "France",
        "Image": "https://d2k6fvhyk5xgx.cloudfront.net/images/creed-neroli-sauvage.jpg",
        "Gender": "unisex",
        "Price": 359.99, 
         "countInStock" : 5, 
    },
    {
        "id":4,
        "Name": "Dior Sauvage Elixir",
        "Brand": "Christian Dior",
        "Year": "2021",
        "rating": "4",
        "Country": "France",
        "Image": "https://d2k6fvhyk5xgx.cloudfront.net/images/dior-sauvage-elixir.jpg",
        "Gender": "men",
        "Price": 259.99,
        "countInStock" : 5,
    },
    {
        "id":5,
        "Name": "Eau Sauvage Parfum",
        "Brand": "Christian Dior",
        "Year": "2012",
        "rating": "4",
        "Country": "France",
        "Image": "https://d2k6fvhyk5xgx.cloudfront.net/images/eau-sauvage-parfum.jpg",
        "Gender": "men",
        "Price": 196.99,
         "countInStock" : 5,
    },
    {
        "id":6,
        "Name": "Roberto Capucci L'Homme Sauvage",
        "Brand": "Roberto Capucci",
        "Year": "2016",
        "rating": "4",
        "Country": "Italy",
        "Image": "https://d2k6fvhyk5xgx.cloudfront.net/images/roberto-capucci-lhomme-sauvage.jpg",
        "Gender": "men",
        "Price": 42.99,
         "countInStock" : 5,
    },
    {
        "id":7,
        "Name": "Souffle Sauvage unisex",
        "Brand": "Bissoumine",
        "Year": "2010",
        "rating": "3",
        "Country": "France",
        "Image": "https://d2k6fvhyk5xgx.cloudfront.net/images/souffle-sauvage-bissoumine-unisex.jpg",
        "Gender": "unisex",
        "Price": 280,
         "countInStock" : 5,
     
    },
    {
        "id":8,
        "Name": "Dior Sauvage Eau Forte",
        "Brand": "Christian Dior",
        "Year": "1990",
        "rating": "4",
        "Country": "France",
        "Image": "https://d2k6fvhyk5xgx.cloudfront.net/images/dior-sauvage-eau-forte.jpg",
        "Gender": "men",
        "Price": 299.99,
         "countInStock" : 5,
    },

    {
        "id":9,
        "Name": "Lavande Sauvage unisex",
        "Brand": "Reflexion",
        "Year": "214",
        "rating": "4",
        "Country": "France",
        "Image": "https://d2k6fvhyk5xgx.cloudfront.net/images/lavande-sauvage-reflexion-unisex.jpg",
        "Gender": "unisex",
        "Price": 300,
         "countInStock" : 5,
    }
]


